---
# tasks file for provision/roles/pxc-sst-user

- mysql_user:
    login_user: root
    login_password: {{ mysql_root_pass }}
    name: sstuser
    password: {{ mysql_sstuser_pass }}
    priv: '*.*:RELOAD,LOCK TABLES,PROCESS,REPLICATION CLIENT'
    state: present
