---
# tasks file for provision/roles/sysbench
- name: Install Sysbench
  yum:
    name:
      - sysbench
    state: latest
    
- name: Get Sysbench-TPCC
  git:
    repo: 'https://github.com/Percona-Lab/sysbench-tpcc.git'
    dest: /opt/sysbench-tpcc
