---
- hosts: extra
  gather_facts: yes
  become: true
  roles:
  - common
  - pmm-client

- hosts: app-server
  gather_facts: yes
  become: true
  roles:
    - sysbench
    - sysbench-pg
    - sysbench-mysql
    - proxysql
