---
- hosts: mongo_servers
  gather_facts: yes
  become: true
  roles:
  - common
#  - pmm-client
  - mongod

- hosts: mongoc_servers
  gather_facts: yes
  become: true
  roles:
  - role: mongoc

- hosts: mongos_servers
  gather_facts: yes
  become: true
  roles:
  - role: mongos

#- hosts: pmm_client_servers
#  gather_facts: yes
#  become: true
#  ignore_errors: true
#  roles:
#    - pmm-client-mongo
