---
- hosts: mysql
  gather_facts: yes
  become: true
  roles:
  - common
#  - pmm-client

- hosts: pxc-node1
  vars:
    hostname: 'node1'
    ip_address: '10.0.0.21'
  gather_facts: yes
  become: true
  roles:
    - pxc-node
    - mysql-root-pwd
    - mysql-my-cnf
    - pxc-sst-user
    - mysql-plugins
    - mysql-replication-user
#    - pmm-client-mysql
    - mysql-sysbench
    - proxysql-user

- hosts: pxc-node2
  vars:
    hostname: 'node2'
    ip_address: '10.0.0.22'
  gather_facts: yes
  become: true
  roles:
    - pxc-node
    - mysql-my-cnf
#    - pmm-client-mysql

- hosts: pxc-node3
  vars:
    hostname: 'node3'
    ip_address: '10.0.0.23'
  gather_facts: yes
  become: true
  roles:
    - pxc-node
    - mysql-my-cnf
#    - pmm-client-mysql

- hosts: mysql-replica
  gather_facts: yes
  become: true
  roles:
    - mysql-replica
    - mysql-root-pwd
    - mysql-my-cnf
    - mysql-plugins
    - mysql-replicate
#    - pmm-client-mysql
