---
# tasks file for provision/roles/pmm-server

- name: Copy the PMM server install script
  become: true
  copy: src=get-pmm.sh dest=/tmp/secret
  mode: 0700

- name: Execute PMM install script
  command: "/bin/sh /tmp/get-pmm.sh"
  args:
    chdir: /root
