---
# tasks file for provision/roles/pmm-client-pg

- name: Add new configuration to "pg_hba.conf" to allow local connection for pmm
  lineinfile:
    regexp: '^host  all  pmm'
    insertbefore: '^local   all             all'
    line: 'host  all  pmm  ::1/128  md5'
    path: /var/lib/pgsql/10/data/pg_hba.conf
  tags: pmm-client-pg

- name: Reload PostgreSQL
  service:
    name: postgresql-10
    state: reloaded
  tags: pmm-client-pg

- name: Configure PMM to monitor PostgreSQL
  shell: pmm-admin add postgresql --host=localhost --user pmm --password 'pmm'
  tags: pmm-client-pg

