---
# tasks file for provision/roles/pmm-client-pg
- name: Setup PMM agent
  shell: pmm-admin config --server-insecure-tls "{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}" --server-url=https://admin:admin@{{ pmm_ip_address }}:443/ --force
  tags: pmm-client


- name: Add new configuration to "pg_hba.conf" to allow local connection for pmm
  lineinfile:
    regexp: '^host  all  pmm'
    insertbefore: '^local   all             all'
    line: 'host  all  pmm  ::1/128  md5'
    path: /var/lib/pgsql/11/data/pg_hba.conf
  tags: pmm-client-pg

- name: Reload PostgreSQL
  service:
    name: postgresql-11
    state: reloaded
  tags: pmm-client-pg

- name: Configure PMM to monitor PostgreSQL
  ignore_errors: true
  shell: pmm-admin add postgresql --username=pmm --password='{{ postgres_pmm_pass }}' --server-url=https://admin:admin@{{ pmm_ip_address }}:443/ --skip-connection-check --server-insecure-tls localhost:5432
  tags: pmm-client-pg
