---
# tasks file for provision/roles/mysql-replication-user

# Replication user
- name: Create replication user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    name: repl
    password: "{{ mysql_repl_pass }}"
    host: '10.0.0.%'
    priv: '*.*:REPLICATION SLAVE,REPLICATION CLIENT'
    state: present
