---
# tasks file for provision/roles/mysql-replication-user

# Replication user
- name: Create replication user
  mysql_user:
    login_user: root
    login_password: percona18live
    name: repl
    password: percona18live
    host: '10.0.0.%'
    priv: '*.*:REPLICATION SLAVE,REPLICATION CLIENT'
    state: present

