---
# tasks file for provision/roles/pmm-client-mysql

- name: Setup PMM agent
  shell: pmm-admin config --server=10.0.0.13
  tags: pmm-client


- name: Configure PMM to monitor MySQL
  shell: pmm-admin add mysql --host=localhost --user pmm --password 'percona18live'
  tags: pmm-client-mysql
