---
# tasks file for provision/roles/pmm-client-mysql

- name: Setup PMM agent
  shell: pmm-admin config --server-insecure-tls "{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}" --server-url=https://admin:admin@{{ pmm_ip_address }}:443/ --force
  tags: pmm-client-mysql


- name: Configure PMM to monitor MySQL
  shell: pmm-admin add mysql --host=localhost --username=pmm --password='{{ mysql_root_pass }}' --server-url=https://admin:admin@{{ pmm_ip_address }}:443/ --skip-connection-check
  tags: pmm-client-mysql
