---
# tasks file for provision/roles/pg-replica

- name: Stop PostgreSQL
  service:
    name: postgresql-10
    state: stopped

- name: Reset data directory
  shell: rm -fr /var/lib/pgsql/10/data/*

- name: Execute base backup
  become_user: postgres
  shell: export PGPASSWORD="replicant" && /usr/bin/pg_basebackup -h 10.0.0.10 -U replicant -D /var/lib/pgsql/10/data -P -v 2>&1

- name: add new configuration "recovery.conf"
  become_user: postgres
  blockinfile:
    create: yes
    dest: /var/lib/pgsql/10/data/recovery.conf
    block: |
      standby_mode = 'on'
      primary_conninfo = 'user=replicant password=replicant host=10.0.0.10 port=5432 sslmode=prefer'
      recovery_target_timeline = 'latest'

- name: Start PostgreSQL
  service:
    name: postgresql-10
    state: started

