---
# tasks file for provision/roles/mysql-pmm-user
- name: Create PMM user
  mysql_user:
    login_user: root
    login_password: percona18live
    name: pmm
    password: percona18live
    host: 'localhost'
    priv: '*.*:SELECT,PROCESS,SUPER,REPLICATION CLIENT'
    state: present

