---
# tasks file for provision/roles/pg-master

# Sysbench database and user

- name: create ROLE sysbench
  become_user: postgres
  postgresql_user:
    login_unix_socket: /tmp
    name: sysbench
    password: sysbench
    encrypted: yes
  tags: sysbench

- name: create sysbench database
  become_user: postgres
  postgresql_db:
    login_unix_socket: /tmp
    name: sysbench
    owner: sysbench
  tags: sysbench

# PMM client, schema and privileges

- name: create role PMM
  become_user: postgres
  postgresql_user:
    login_unix_socket: /tmp
    name: pmm
    password: "{{ postgres_pmm_pass }"
    encrypted: yes
    role_attr_flags: SUPERUSER
  tags: pmm-client

#- name: create schema PMM
#  become_user: postgres
#  postgresql_schema:
#    login_unix_socket: /tmp
#    name: pmm
#    owner: pmm
#  tags: pmm-client



#CREATE USER "pmm" WITH PASSWORD 'password';
####ALTER USER "pmm" SET SEARCH_PATH TO "pmm",pg_catalog;
#CREATE SCHEMA pmm authorization pmm;
#  ???? CREATE OR REPLACE VIEW "pmm".pg_stat_activity AS SELECT * from pg_catalog.pg_stat_activity;
###GRANT SELECT ON "pmm".pg_stat_activity TO "pmm";
#  ???? CREATE OR REPLACE VIEW "pmm".pg_stat_replication AS SELECT * from pg_catalog.pg_stat_replication;
###GRANT SELECT ON "pmm".pg_stat_replication TO "pmm";
#ALTER USER pmm WITH SUPERUSER;
