- name: Setup PMM agent
  shell: pmm-admin config --server-insecure-tls "{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}" --server-url=https://admin:admin@{{ pmm_ip_address }}:443/ --force
  tags: pmm-client-mongo

- name: Create the file to add PMM service
  become: true
  template: src=add_pmm_service.j2 dest=/tmp/add_pmm_service.sh
  ignore_errors: yes

- name: Configure PMM to monitor ProxySQL
  shell: bash /tmp/add_pmm_service.sh
  ignore_errors: yes
