---
# tasks file for provision/roles/sysbench-mysql

- name: Run sysbench-tpcc in 'prepare' mode
  ignore_errors: true
  shell: "sysbench /opt/sysbench-tpcc/tpcc.lua --mysql-host=10.0.0.21 --mysql-user=sysbench --mysql-password=sysbench --mysql-db=sysbench --time=20 --threads=1 --report-interval=1 --tables=4 --scale=1 --use_fk=0 --trx_level=RC --db-driver=mysql prepare"
  args:
    chdir: /opt/sysbench-tpcc
  tags: sysbench-mysql

## Deploy MySQL sysbench load file
- name: Create the user file1
  become: true
  template: src=load1.j2 dest=/tmp/load1.sh

- name: Create the user file2
  become: true
  template: src=load2.j2 dest=/tmp/load2.sh

- name: Create the user file3
  become: true
  template: src=load3.j2 dest=/tmp/load3.sh

- name: "Configure sysbench-tpcc load1"
  ignore_errors: true
  cron:
    minute: "*/3"
    job: "bash /tmp/load1.sh"
  tags: sysbench-mysql

- name: "Configure sysbench-tpcc load1"
  ignore_errors: true
  cron:
    minute: "*/4"
    job: "bash /tmp/load1.sh"
  tags: sysbench-mysql

- name: "Configure sysbench-tpcc load2"
  ignore_errors: true
  cron:
    minute: "*/5"
    job: "bash /tmp/load2.sh"
  tags: sysbench-mysql

- name: "Configure sysbench-tpcc load3"
  ignore_errors: true
  cron:
    minute: "*/7"
    job: "bash /tmp/load3.sh"
  tags: sysbench-mysql
