---
# tasks file for provision/roles/sysbench-pg

- name: Run sysbench-tpcc in 'prepare' mode
  ignore_errors: true
  shell: "sysbench /opt/sysbench-tpcc/tpcc.lua --pgsql-host=10.0.0.10 --pgsql-user=sysbench --pgsql-password=sysbench --pgsql-db=sysbench --time=10 --threads=1 --report-interval=1 --tables=4 --scale=1 --use_fk=0 --trx_level=RC --db-driver=pgsql prepare"
  args:
    chdir: /opt/sysbench-tpcc
  tags: sysbench-pg

- name: "Configure sysbench-tpcc to run every 3 minutes"
  ignore_errors: true
  cron:
    minute: "*/3"
    job: "cd /opt/sysbench-tpcc && /usr/bin/env /usr/bin/sysbench tpcc.lua --pgsql-host=10.0.0.10 --pgsql-user=sysbench --pgsql-password=sysbench --pgsql-db=sysbench --time=20 --threads=1 --report-interval=1 --tables=4 --scale=1 --use_fk=0 --trx_level=RC --db-driver=pgsql run"
  tags: sysbench-pg
