---
# tasks file for provision/roles/pg
- name: install ProxySQL 2.0 rpm from a remote repo
  yum:
    name: https://github.com/sysown/proxysql/releases/download/v2.0.6/proxysql-2.0.6-1-centos7.x86_64.rpm
    state: present


- name: start PostgreSQL
  service:
    name: proxysql
    state: started
    enabled: yes

- name: create ROLE replicant
  become_user: postgres
  postgresql_user:
    db: postgres
    login_unix_socket: /tmp
    name: replicant
    password: replicant
    role_attr_flags: LOGIN,REPLICATION
    encrypted: yes

- name: add new configuration to "postgresql.conf"
  blockinfile:
    dest: /var/lib/pgsql/11/data/postgresql.conf
    block: |
      include 'server.conf'

- name: add new configuration to "server.conf"
  become_user: postgres
  blockinfile:
    create: yes
    dest: /var/lib/pgsql/11/data/server.conf
    block: |
      listen_addresses = '*'
      wal_level = replica
      max_wal_senders = 6
      wal_keep_segments = 11
      hot_standby = on

- name: add new configuration to "pg_hba.conf"
  blockinfile:
    dest: /var/lib/pgsql/11/data/pg_hba.conf
    block: |
      host    all             all             0.0.0.0/0                md5
      host    replication     replicant       0.0.0.0/0                md5

##- name: clear ident and peer entries on "pg_hba.conf"
##  lineinfile:
##    dest: /var/lib/pgsql/11/data/pg_hba.conf
##    regexp: "ident"
##    state: absent
##
##- name: clear ident and peer entries on "pg_hba.conf"
##  lineinfile:
##    dest: /var/lib/pgsql/11/data/pg_hba.conf
##    regexp: "peer"
##    state: absent

- name: update environment variables in UNIX account postgres
  blockinfile:
    create: yes
    dest: /var/lib/pgsql/.pgsql_profile
    block: |
      export PGHOST=/tmp PAGER=less PGDATA=/var/lib/pgsql/11/data

- name: Restart PostgreSQL
  service:
    name: postgresql-11
    state: restarted
