---
# tasks file for provision/roles/pg
- name: Install ProxySQL 2.0 rpm from a remote repo
  yum:
    name: https://github.com/sysown/proxysql/releases/download/v2.0.6/proxysql-2.0.6-1-centos7.x86_64.rpm
    state: present
  become: true

- name: Install MySQL Client
  yum:
    name: ['Percona-Server-client-57']
    state: latest
  become: true

- name: start ProxySQL
  service:
    name: proxysql
    state: started
    enabled: yes

- name: Create the ProxySQL config file
  template: src=config_proxysql.j2 dest=/tmp/config_proxysql.sql
  become: true

- name: Set Proxysql
  shell: mysql -uadmin -padmin -h 127.0.0.1 -P 6032 < /tmp/config_proxysql.sql
  become: true
