---
- name: Setup PMM agent
  shell: pmm-admin config --server-insecure-tls "{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}" --server-url=https://admin:admin@{{ pmm_ip_address }}:443/ --force
  tags: pmm-client-mongo

  # tasks file for provision/roles/pmm-client-mongo
- name: Create the file to create PMM user in MongoDB
  template: src=create_user.j2 dest=/tmp/create_user.js
  when: ("{{ inventory_hostname }}" == "mongo1")
  ignore_errors: yes
  tags: pmm-client-mongo

- name: Create the file to add PMM service mongod
  become: true
  template: src=add_pmm_service.j2 dest=/tmp/add_pmm_service{{ item }}.sh owner=mongod group=mongod
  with_items: "{{ mongod_ports }}"
  tags: pmm-client-mongo
  ignore_errors: yes

- name: Create the file to add PMM service mongos
  become: true
  template: src=add_pmm_service.j2 dest=/tmp/add_pmm_service{{ mongos_ports }}.sh owner=mongod group=mongod
  tags: pmm-client-mongo
  ignore_errors: yes

- name: Create the file to set the profiling on all mongod servers
  template: src=set_profiling.j2 dest=/tmp/set_profiling.js
  delegate_to: '{{ item }}'
  with_items: "{{ groups['pmm_client_servers'] }}"
  tags: pmm-client-mongo


- name: Set profiling for mongod
  shell: /usr/bin/mongo  localhost:{{ mongod_port }}/admin -uadmin -p{{ mongo_admin_pass }}  /tmp/set_profiling.js
  with_items: "{{ mongod_ports }}"
  tags: pmm-client-mongo

- name: Create PMM user mongod
  shell: /usr/bin/mongo  localhost:{{ item }}/admin -uadmin -p{{ mongo_admin_pass }}  /tmp/create_user.js
  with_items: "{{ mongod_ports }}"
  when: ("{{ inventory_hostname }}" == "mongo1")
  tags: pmm-client-mongo
  ignore_errors: yes

- name: Create PMM user mongos
  shell: /usr/bin/mongo  localhost:{{ item }}/admin -uadmin -p{{ mongo_admin_pass }}  /tmp/create_user.js
  with_items: "{{ mongos_ports }}"
  when: ("{{ inventory_hostname }}" == "mongo1")
  tags: pmm-client-mongo
  ignore_errors: yes

- name: Configure PMM to monitor mongod
  shell: bash /tmp/add_pmm_service{{ item }}.sh
  with_items: "{{ mongod_ports }}"
  tags: pmm-client-mongo
  ignore_errors: yes

- name: Configure PMM to monitor mongos
  shell: bash /tmp/add_pmm_service{{ item }}.sh
  with_items: "{{ mongos_ports }}"
  tags: pmm-client-mongo
  ignore_errors: yes
