---
- name: Setup PMM agent
  shell: pmm-admin config --server-insecure-tls "{{ hostvars[item]['ansible_eth1']['ipv4']['address'] }}" --server-url=https://admin:admin@{{ pmm_ip_address }}:443/ --force
  delegate_to: '{{ item }}'
  with_items: "{{ groups['pmm_client_servers'] }}"
  tags: pmm-client-mongo

  # tasks file for provision/roles/pmm-client-mongo
- name: Create the file to create PMM user in MongoDB
  template: src=create_user.j2 dest=/tmp/create_user.js
  delegate_to: '{{ item }}'
  with_items: "{{ groups['pmm_client_servers'] }}"
  tags: pmm-client-mongo

- name: Create the file to add PMM service
  become: true
  template: src=add_pmm_service.j2 dest=/tmp/add_pmm_service{{ mongod_port }}.sh owner=mongod group=mongod
  delegate_to: '{{ item }}'
  with_items: "{{ groups['pmm_client_servers'] }}"
  tags: pmm-client-mongo

- name: Create the file to set the profiling on all mongod servers
  template: src=set_profiling.j2 dest=/tmp/set_profiling.js
  delegate_to: '{{ item }}'
  with_items: "{{ groups['pmm_client_servers'] }}"
  tags: pmm-client-mongo


- name: Set profiling
  shell: /usr/bin/mongo  localhost:{{ mongod_port }}/admin -uadmin -p{{ mongo_admin_pass }}  /tmp/set_profiling.js
  delegate_to: '{{ item }}'
  with_items: "{{ groups['pmm_client_servers'] }}"
  tags: pmm-client-mongo

- name: Create user
  shell: /usr/bin/mongo  localhost:{{ item }}/admin -uadmin -p{{ mongo_admin_pass }}  /tmp/create_user.js
  delegate_to: '{{ item }}'
  with_items: "{{ groups['pmm_client_servers'][mongod_port] }}"
  tags: pmm-client-mongo

- name: Configure PMM to monitor MongoDB
  shell: bash /tmp/add_pmm_service{{ mongod_port }}.sh
  delegate_to: '{{ item }}'
  with_items: "{{ groups['pmm_client_servers'] }}"
  tags: pmm-client-mongo
